version: 2.1

orbs:
  aws-eks: circleci/aws-eks@0.2.0
  aws-ecr: circleci/aws-ecr@3.1.0
  kubernetes: circleci/kubernetes@0.3.0

jobs:
  deploy-application:
    executor: aws-eks/python3
    steps:
      - checkout

workflows:
  version: 2
  deployment:
    jobs:
      # list jobs and parameters
      - deploy-application

