apiVersion: v1
kind: Service
metadata:
  name: demo-circle-k8s
  labels:
    app: demo
spec:
  # automatically create an external load-balanced IP for the service.
  # type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: demo
